### ISSUE TITLE
Doesn't work with templates with VS Macros in them

### ISSUE THREAD

**Issue by MelGrubb** [clariuslabs/TransformOnBuild#1]
This may not be possible via the TextTransform.exe tool. I have templates that do some reflection over other assemblies in my solution. To find them, they reference assemblies using paths constructed from Visual Studio macros like this:

<#@ assembly name="$(SolutionDir)<PROJECTNAME>\bin\Debug<PROJECTNAME>.dll" #>

Running this from inside Visual Studio works just fine, but has to be done manually rather than the output just always being up to date. TextTransform.exe has no idea what "$(SolutionDir)" means, though.

As I said, this may not be possible, but if you have any kind of other alternate approach that would make this work, I'd love to hear it.

**Comment by Lucasjuv** [comment]
HTH, I have worked around this creating a simple powershell script to replace macros before running the texttransform tool and if you run the tool from the same folder as the .tt files Host.ResolvePath with relative paths will work. here is a sample of the powershell script:

```
$t4files = Get-ChildItem -Path .\ -Filter *.tt

Foreach ($file in $t4files) {
	(Get-Content $file) -replace "\$\(TargetPath\)","<YourAssemblyPath>" -replace "\$\(TargetDir\)","<YourTargetDir>" | Set-Content $file	
			
	.\TextTransform.exe $file
	
	(Get-Content $file) -replace "<YourAssemblyPath>","`$(TargetPath)" -replace "<YourTargetPDir>","`$(TargetDir)" | Set-Content $file
}
```

Note that the paths can also be relative.
