### ISSUE TITLE
Please list the prerequisites required for a build server

### ISSUE THREAD

**Issue by mikeblakeuk** [clariuslabs/TransformOnBuild#13]
Can you please provide more details about installing this on a build server such as Team City
What do I need to install?
Thanks

EXEC Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.10.0, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
C:\BuildAgent\work\myproject\packages\Clarius.TransformOnBuild.1.1.12\build\Clarius.TransformOnBuild.targets(45, 9): error MSB3073: The command ""C:\Program Files (x86)\Common Files\Microsoft Shared\TextTemplating\10.0\TextTransform.exe" "C:\BuildAgent\work\5e6f4a4dcf97bd47\myproject\WebsiteUnderTest\GenerateWebTests.tt"" exited with code 1.

**Comment by mnaoumov** [comment]
List of the required files

Microsoft.VisualStudio.TextTemplating.*.dll
Microsoft.VisualStudio.TextTemplating.Modeling.*.dll
Microsoft.VisualStudio.TextTemplating.VSHost.*.dll
TextTransform.exe
