### ISSUE TITLE
Transformation error during publishing an app

### ISSUE THREAD

**Issue by rmaziarka** [clariuslabs/TransformOnBuild#39]
Hi,

I have no problem during normal development & build cycle. Transformation is running flawlessly creating js files basis on tt.

Unfortunately the app is throwing an error during publish to my environment:

> TRANSFORMONBUILDTASK        An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
> And nothing more. I cannot go into it and try to solve a problem because there is no log to start investigation.

**Comment by mnaoumov** [comment]
Sorry for such a late delay. Is this issue still happening?

**Comment by mnaoumov** [comment]
Closing as there is no helpful information how to replicate the issue

**Comment by SebLz** [comment]
I have the same problem. It started happening after I added a second tt file in the project. Running the tt files manually work fine.
