### ISSUE TITLE
Server build failing with Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.14.0

### ISSUE THREAD

**Issue by JobaDiniz** [clariuslabs/TransformOnBuild#54]
_(TransformOnBuild target) -> 
  TRANSFORMONBUILDTASK : error : Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [B:\_work\2\s\Automation\Tests\WDG.Automation.WalTests\WDG.Automation.WalTests.csproj]
    1465 Warning(s)
    1 Error(s)_

The build server does not have Visual Studio installed. I even tried to install package `Microsoft.VisualStudio.TextTemplating.VSHost.14` and `Microsoft.VisualStudio.TextTemplating.14`, but the error persists

**Comment by mnaoumov** [comment]
You have same missing assemblies. Take a look https://stackoverflow.com/a/29114963/1074455
