### ISSUE TITLE
Support alternate value for %(None.Generator)

### ISSUE THREAD

**Issue by lencharest** [clariuslabs/TransformOnBuild#7]
Right now, the TransformOnBuild target identifies which files to transform by matching items of type None with Generator metadata equal to 'TextTemplatingFileGenerator' only. So I must assign TextTemplatingFileGenerator (as the value of Custom Tool in file properties) to my `.tt` files in order to get the benefits of TansformOnBuild.

But since TextTemplatingFileGenerator is the name of a custom tool recognized by Visual Studio, every time I edit and save a `.tt` file Visual Studio expands the template and injects the generated file in to my project. I'd rather that not happen.

I could avoid this unwanted design-time code generation if the TransformOnBuild  target recognized some other value for `%(None.Generator)` that does not correspond to a known custom tool. For example, the string 'TransformOnBuild' as follows:

```
    <ItemGroup>
        <_TextTransform Include="@(None)"
            Condition="'%(None.Generator)'=='TextTemplatingFileGenerator' or '%(None.Generator)'=='TransformOnBuild'" />
    </ItemGroup>
```

**Comment by mnaoumov** [comment]
Personally I don't think it is an useful feature. I'll close it for now but if community would ask for it, we'll reopen and discuss

**Comment by mnaoumov** [comment]
I think this feature wouldn't hurt. Initially I thought I'd better to be aligned with Visual Studio implementation. But now I changed my mind
