### ISSUE TITLE
Double quote error

### ISSUE THREAD

**Issue by doubret** [clariuslabs/TransformOnBuild#8]
Hi, i use the package from quite some time now without any troubles.
I notices something strange today, i suspect it is a bug.

When you search for the TextTransform.exe in the msbuild target, there is a leading double quote in the path you're searching for :

<_TransformExe Condition="!Exists('$(_TransformExe)')">$(_CommonProgramFiles)\Microsoft Shared\TextTemplating\10.0\TextTransform.exe"**<--- HERE**</_TransformExe>

All the search seem to fail because of this.

Are the double quotes really supposed to be there ?

**Comment by mnaoumov** [comment]
Seems to be fixed
